name: Deploy API REST in Azure API Center

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  public_api_in_apicenter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Extract OpenAPI metadata
        id: extract
        run: |
          TITLE=$(yq '.info.title' api-specs/openapi.yaml)
          API_ID=$(yq '.info."x-api-id"' api-specs/openapi.yaml)
          
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "api_id=$API_ID" >> $GITHUB_OUTPUT

      - name: Create API (if not exists)
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az apic api register \
            --resource-group rg-articulos \
            --service-name api-center-mv \
            --api-location "api-specs/openapi.yaml" \
            --api-id "${{ steps.extract.outputs.api_id }}" \
            --title "${{ steps.extract.outputs.title }}" \
            --type rest
